---
- name: make sure maintenance directory is present
  file:
    path: "{{ sitewards_server_suicide_base_path }}"
    state: directory
    mode: 0755
    recurse: yes

- name: make sure required script is present
  template:
    src: "{{ item }}"
    dest: "{{ sitewards_server_suicide_base_path }}"
    owner: "{{ sitewards_server_suicide_owner }}"
    group: "{{ sitewards_server_suicide_group }}"
  with_items:
    - monitor.php

- name: make first request to the server to populate access_log
  uri:
    url: "{{ sitewards_server_suicide_warm_up_url }}"
    follow_redirects: none
    status_code: 200, 201, 208, 301, 302
  when: sitewards_server_suicide_warm_up_url != ''

- debug:
    var: sitewards_server_suicide_active
- debug:
    var: "{{ not sitewards_server_suicide_active|bool }}"
    
- name: Create crontask to check for server activity in specified period.
  cron:
    name: monitor server termination
    user: "{{ sitewards_server_suicide_owner }}"
    minute: "{{ sitewards_server_suicide_cronjob_execution_interval }}"
    job: "{{ sitewards_server_suicide_stdin_data_feed }} | php {{ sitewards_server_suicide_base_path }}/monitor.php --termination \"{{ sitewards_server_suicide_termination_url }}\" --logfile \"{{ sitewards_server_suicide_logfile_path }}\" --interval \"{{ sitewards_server_suicide_server_termination_check_interval }}\""
    state: present
    disabled: "{{ not sitewards_server_suicide_active|bool }}"
